server:
  port: 8091

spring:
  application:
    name: ms-solicitud-dominio
  datasource:
    url: jdbc:h2:mem:db_bank
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop